#############################################################################
# Makefile for building: qgolftracker
# Generated by qmake (2.01a) (Qt 4.7.4) on: ti 22. marras 18:48:58 2011
# Project:  qgolftracker.pro
# Template: app
# Command: e:/qtsdk/madde/targets/harmattan-nokia-meego-api/bin/qmake.exe -spec e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qgolftracker.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -O2 -g -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -I/usr/include/applauncherd -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -Ie:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/default -I. -Ie:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/include/qt4/QtCore -Ie:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/include/qt4/QtGui -Ie:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/include/qt4/QtDeclarative -Ie:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/include/qt4 -Imoc
LINK          = g++
LFLAGS        = -pie -rdynamic -Wl,-O1
LIBS          = $(SUBLIBS)  -LE:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib -pie -rdynamic -lmdeclarativecache -lQtDeclarative -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = e:/qtsdk/madde/targets/harmattan-nokia-meego-api/bin/qmake.exe
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp rcc/qrc_res.cpp
OBJECTS       = obj/main.o \
		obj/qrc_res.o
DIST          = e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/g++.conf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/unix.conf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/linux.conf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/qconfig.pri \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		deployment.pri \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/release.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/default_post.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/moc.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/resources.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/uic.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/yacc.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/lex.prf \
		qgolftracker.pro
QMAKE_TARGET  = qgolftracker
DESTDIR       = 
TARGET        = qgolftracker

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qgolftracker.pro  e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/default/qmake.conf e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/g++.conf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/unix.conf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/linux.conf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/qconfig.pri \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt_functions.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt_config.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/default_pre.prf \
		deployment.pri \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/release.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/default_post.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/warn_on.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/unix/thread.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/moc.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/resources.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/uic.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/yacc.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/lex.prf \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib/libQtDeclarative.prl \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib/libQtGui.prl \
		e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib/libQtCore.prl
	$(QMAKE) -spec e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qgolftracker.pro
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/g++.conf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/unix.conf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/common/linux.conf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/qconfig.pri:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt_functions.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt_config.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/default_pre.prf:
deployment.pri:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/release.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/default_post.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qdeclarative-boostable.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/warn_on.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/qt.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/unix/thread.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/moc.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/resources.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/uic.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/yacc.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/features/lex.prf:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib/libQtDeclarative.prl:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib/libQtGui.prl:
e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec e:/QtSDK/Madde/sysroots/harmattan-nokia-meego-arm-sysroot-1134-slim/usr/share/qt4/mkspecs/default -unix -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o Makefile qgolftracker.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/qgolftracker1.0.0 || $(MKDIR) obj/qgolftracker1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/qgolftracker1.0.0/ && $(COPY_FILE) --parents res.qrc obj/qgolftracker1.0.0/ && $(COPY_FILE) --parents main.cpp obj/qgolftracker1.0.0/ && (cd `dirname obj/qgolftracker1.0.0` && $(TAR) qgolftracker1.0.0.tar qgolftracker1.0.0 && $(COMPRESS) qgolftracker1.0.0.tar) && $(MOVE) `dirname obj/qgolftracker1.0.0`/qgolftracker1.0.0.tar.gz . && $(DEL_FILE) -r obj/qgolftracker1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all: rcc/qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_res.cpp
rcc/qrc_res.cpp: res.qrc \
		functions.js \
		qml/ViewbyclubsPage.qml \
		qml/ViewPage.qml \
		qml/ViewMapPage.qml \
		qml/main.qml \
		qml/HelpPage.qml \
		qml/MainPage.qml \
		qml/EditCourses.qml \
		qml/EditClubs.qml \
		qml/DetailsPage.qml \
		qml/RecPage.qml \
		qml/AboutPage.qml \
		images/tee.svg \
		images/logo.svg \
		images/flag.svg
	e:/QtSDK/Madde/targets/harmattan-nokia-meego-api/bin/rcc.exe -name res res.qrc -o rcc/qrc_res.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean 

####### Compile

obj/main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/qrc_res.o: rcc/qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_res.o rcc/qrc_res.cpp

####### Install

install_splashscreen: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/qgolftracker/images/ || $(MKDIR) $(INSTALL_ROOT)/opt/qgolftracker/images/ 
	-$(INSTALL_FILE) c:/Users/timo/Documents/koodaukset/qgolftracker/images/splash.png $(INSTALL_ROOT)/opt/qgolftracker/images/


uninstall_splashscreen:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/qgolftracker/images/splash.png
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qgolftracker/images/ 


install_desktopfile: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) c:/Users/timo/Documents/koodaukset/qgolftracker/qgolftracker.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_desktopfile:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/qgolftracker.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 
	-$(INSTALL_FILE) c:/Users/timo/Documents/koodaukset/qgolftracker/qgolftracker.png $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/qgolftracker.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/64x64/apps/ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/opt/qgolftracker/bin/ || $(MKDIR) $(INSTALL_ROOT)/opt/qgolftracker/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/qgolftracker/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/qgolftracker/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/qgolftracker/bin/ 


install:  install_splashscreen install_desktopfile install_icon install_target  FORCE

uninstall: uninstall_splashscreen uninstall_desktopfile uninstall_icon uninstall_target   FORCE

FORCE:

